format = "$all"

add_newline = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[V](bold green)"
vimcmd_replace_one_symbol = "[V](bold purple)"
vimcmd_replace_symbol = "[V](bold purple)"
vimcmd_visual_symbol = "[V](bold yellow)"

[package]
display_private = true

[directory]
truncation_length = 999999
truncate_to_repo = true

